### ISSUE TITLE
device unresponsive

### ISSUE THREAD

**Issue by ayushjain4484** [DarkPixelWolf/Espalexa-Python#1]
Hi,
thanks alot for your work,
I am trying to use Espalexa-Python to control RGB LED strip with raspberry pi but after discovering devices I am unable to do any operation with it.
and also both devices (with color and without color) are showing as simple light switch without brightness control or color changing option.
please assist and if you could share code for any working example, i would be very helpful.

Thanks in Advance.

**Comment by PyxelFox** [comment]
If I recall correctly there was an issue with the Espalexa library regarding color devices, the brightness worked for me though. I will look into it tomorrow morning (11pm here) and update the python port to the latest Espalexa version.

**Comment by ayushjain4484** [comment]
Thanks alot that would be really helpful.

**Comment by PyxelFox** [comment]
The library is now up to date! (Espalexa 2.4.3)

I couldn't test the library to its full extend, but dimmable and color devices worked fine for me.
If the rgb values aren't correct please tell me and I will look into it again.

If you need an example on how to use the library in your python project please read the README or use the example code provided in `example.py`.

~~There are still some debug messages that I need to remove, so please ignore them.~~

**Comment by ayushjain4484** [comment]
Hey,
Thank you for the quick response.
I tested the updated library and ran into some error while testing it for the device 'light with color'.
I am able to turn it on,off and dim the light using the app , but when i set light to particular color an execption message is received and the app shows that the device is malfunctioning
__________________________________Response____________________________
Exception happened during processing of request from ('192.168.1.111', 52307)
Traceback (most recent call last):
  File "/usr/lib/python3.5/socketserver.py", line 313, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib/python3.5/socketserver.py", line 341, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib/python3.5/socketserver.py", line 354, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.5/socketserver.py", line 681, in __init__
    self.handle()
  File "/usr/lib/python3.5/http/server.py", line 422, in handle
    self.handle_one_request()
  File "/usr/lib/python3.5/http/server.py", line 410, in handle_one_request
    method()
  File "/home/pi/Desktop/Espalexa-Python/espalexa.py", line 305, in do_GET
    self.outer.servePage(self)
  File "/home/pi/Desktop/Espalexa-Python/espalexa.py", line 357, in servePage
    res = res + "Value of device " + str(i + 1) + " (" + self.devices[i].getName() + "): " + str(self.devices[i].getValue()) + " (" + self.getTypeString(devices[i].getType())
NameError: name 'devices' is not defined
______________________________________________

**Comment by PyxelFox** [comment]
I updated the library, however this error only affected the Espalexa status page.

Regarding your problem with controlling the lights:
Did you delete them from the alexa app and rediscovered them? If so, could you share some code how you implemented the library? Or enable the Debug mode of Espalexa and upload the outputs after discovery and controlling to pastebin or paste it here.

I tested the example.py again with my echo dot and it worked without any problems.

Output of example.py:
```Brightness: 255
16763648
Red: 255, Green: 203, Blue: 0
Brightness: 255
16711692
Red: 255, Green: 0, Blue: 12
Brightness: 255
16755218
Red: 255, Green: 170, Blue: 18
Brightness: 255
16720465
Red: 255, Green: 34, Blue: 81
Brightness: 255
16776719
Red: 255, Green: 254, Blue: 15
Brightness: 255
65279
Red: 0, Green: 254, Blue: 255
Brightness: 105
65279
Red: 0, Green: 254, Blue: 255

**Comment by ayushjain4484** [comment]
i am using the same code example.py as attached with the library and still driving into error could you tell me how to enable the debug mode.

**Comment by PyxelFox** [comment]
It is discribed in the readme:
instead of 
`espalexa = Espalexa()`
write
`espalexa = Espalexa(DEBUG = True)`

**Comment by ayushjain4484** [comment]
i am getting this error when trying to change the color enabled the debug mode

______________________________________________________________________

AlexaApiCall
/api/babb42713ae143f88175471965f2a1a6/lights/191716546/state
{"hue":3095,"sat":132}
- Is API call
Ok
- Checked USERNAME request
-! CONTROL REQUEST
192.168.1.104 - - [17/Jul/2019 13:27:41] "PUT /api/babb42713ae143f88175471965f2a1a6/lights/191716546/state HTTP/1.1" 200 -

ls191716546
----------------------------------------
Exception happened during processing of request from ('192.168.1.104', 48902)
Traceback (most recent call last):
  File "/usr/lib/python3.5/socketserver.py", line 313, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib/python3.5/socketserver.py", line 341, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib/python3.5/socketserver.py", line 354, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.5/socketserver.py", line 681, in __init__
    self.handle()
  File "/usr/lib/python3.5/http/server.py", line 422, in handle
    self.handle_one_request()
  File "/usr/lib/python3.5/http/server.py", line 410, in handle_one_request
    method()
  File "/home/pi/Desktop/Espalexa-Python/espalexa.py", line 338, in do_PUT
    self.outer.handleAlexaApiCall(path, post_body.decode('utf-8'), self)
  File "/home/pi/Desktop/Espalexa-Python/espalexa.py", line 547, in handleAlexaApiCall
    self.devices[devId].setColor(int(body[(body.find("hue") + 5):]), int(body[(body.find("sat") + 5):]))
ValueError: invalid literal for int() with base 10: '3095,"sat":132}'
----------------------------------------
AlexaApiCall
/api/babb42713ae143f88175471965f2a1a6/lights/191716546

- Is API call
Ok
- Checked USERNAME request
- Checked CONTROL request
-! LIGHTS REQUEST
l191716546
192.168.1.104 - - [17/Jul/2019 13:27:41] "GET /api/babb42713ae143f88175471965f2a1a6/lights/191716546 HTTP/1.1" 200 -

AlexaApiCall
/api/babb42713ae143f88175471965f2a1a6/lights/191716546

- Is API call
Ok
- Checked USERNAME request
- Checked CONTROL request
-! LIGHTS REQUEST
l191716546
192.168.1.104 - - [17/Jul/2019 13:27:42] "GET /api/babb42713ae143f88175471965f2a1a6/lights/191716546 HTTP/1.1" 200 -

**Comment by PyxelFox** [comment]
Allright, thank you for the error log.
Sadly my setup didnt't behave like yours, but that is no problem, I found the issue and fixed it (well, I can't tell if there are more porblems to it, as my setup behaves different).

**Comment by ayushjain4484** [comment]
It is working perfectly now.

Awesome work i really appriciate your help for this.

Thank you soo much... @DarkPixelWolf

**Comment by PyxelFox** [comment]
No problem, thanks for sharing the error log.

I will close this issue now since it is solved.

If you have any other questions feel free to open a new one.

**Comment by ayushjain4484** [comment]
Hey @DarkPixelWolf  i encountered an new issue related to the color all the colors are working fine except the color inside shades of white they give me exactly the same error which i was receiving before

Else everything is working fine can you please fix that too..:)

**Comment by PyxelFox** [comment]
Could you paste a new debug log again? 
It tells me what alexa send and what exactly is the issue.

**Comment by ayushjain4484** [comment]
Here you go

-------------------------------------
AlexaApiCall
/api/babb42713ae143f88175471965f2a1a6/lights/191716546/state
{"ct":383}
- Is API call
Ok
- Checked USERNAME request
-! CONTROL REQUEST
192.168.1.104 - - [17/Jul/2019 14:18:36] "PUT /api/babb42713ae143f88175471965f2a1a6/lights/191716546/state HTTP/1.1" 200 -

ls191716546
----------------------------------------
Exception happened during processing of request from ('192.168.1.104', 51238)
Traceback (most recent call last):
  File "/usr/lib/python3.5/socketserver.py", line 313, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib/python3.5/socketserver.py", line 341, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib/python3.5/socketserver.py", line 354, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.5/socketserver.py", line 681, in __init__
    self.handle()
  File "/usr/lib/python3.5/http/server.py", line 422, in handle
    self.handle_one_request()
  File "/usr/lib/python3.5/http/server.py", line 410, in handle_one_request
    method()
  File "/home/pi/Desktop/Espalexa-Python/espalexa.py", line 338, in do_PUT
    self.outer.handleAlexaApiCall(path, post_body.decode('utf-8'), self)
  File "/home/pi/Desktop/Espalexa-Python/espalexa.py", line 550, in handleAlexaApiCall
    self.devices[devId].setColorCT(int(body[(body.find("ct") + 4):]))
ValueError: invalid literal for int() with base 10: '383}'
----------------------------------------
AlexaApiCall
/api/babb42713ae143f88175471965f2a1a6/lights/191716546

**Comment by PyxelFox** [comment]
Should be fixed.

**Comment by ayushjain4484** [comment]
Its working perfectly now 

Once again thank you for your help @DarkPixelWolf  :)
