### ISSUE TITLE
Alexa not able to control Groups...!!

### ISSUE THREAD

**Issue by ayushjain4484** [DarkPixelWolf/Espalexa-Python#2]
Hey @DarkPixelWolf ,

Sorry for the trouble again i have discovered an new issue with the library.
Alexa is able to turn on  all the lights in the group but is unable to turn all the lights in the group off.

Please can you help me with this too.

**Comment by PyxelFox** [comment]
It works for me, got any errors?

**Comment by ayushjain4484** [comment]
i have created 4 devices all are of color type they worked when i set them on in a group but they wont go off.

 when i try to off them , some devices becomes unresponsive

**Comment by PyxelFox** [comment]
Still works for me.
Any errors in debug, on what type of device are you running the library?

**Comment by ayushjain4484** [comment]
No there are no error in the debug.

 I am running them for 'light with color type' the thing which i have noticed is that when we try to operate the group using alexa , the responses are delayed and they dont reflect the correct status on the app too and after some time some of the device become unresponsive.

**Comment by PyxelFox** [comment]
This might be due to a bad connection or a slow device. 

My Alexa is able to check and set the status of the light and the changes happen with nearly zero delay.
I hooked up 20 color lights in a group and they are all working just fine.

**Comment by ayushjain4484** [comment]
This is what i have noticed when i turn them on then all strip should display 255 (i.e on with maximum brightness) but it is not so in here is this due to an connectivity issue..??
![Untitled](https://user-images.githubusercontent.com/23170844/61384433-39ebe100-a8ce-11e9-8732-39bdd0763f2b.png)
![WhatsApp Image 2019-07-17 at 8 06 09 PM](https://user-images.githubusercontent.com/23170844/61384548-715a8d80-a8ce-11e9-8bd1-45c45b85ced0.jpeg)

**Comment by PyxelFox** [comment]
This might be a limitation by your network, I don't know for sure. Alexa is sending one request per lamp, not one for all. 
![Status](https://user-images.githubusercontent.com/25132737/61386037-cfc64280-a8b3-11e9-9362-e43bac977c00.png)
I defined 12 color devices, 10 (1-10) of them are in the same group and are reacting if I change them in the app. It even works with brightness and color.

**Comment by ayushjain4484** [comment]
i tried it again connecting it with different router and an different service provider no luck 

still facing the same issue the values on the page aren't updating and on the app it shows that the device are malfunctioned even the debuger doesnot output the responses as it used to do before.
 
![WhatsApp Image 2019-07-17 at 9 03 56 PM](https://user-images.githubusercontent.com/23170844/61389578-ca2e2400-a8d6-11e9-98fc-177eb43cfb2b.jpeg)
![Capture](https://user-images.githubusercontent.com/23170844/61389754-12e5dd00-a8d7-11e9-9671-b41e7fc3cdd7.PNG)
![Untitled](https://user-images.githubusercontent.com/23170844/61389237-2d6b8680-a8d6-11e9-9d89-817811d57978.png)

The issue starts when when put the lights in an group in an alexa app if we don't add them in a group and use them idividualy they work fine 

I have another findings which i have came across when we try to control the light from the app the responses work's well but as soon as i navigate to http://[ip-address]/espalexa page to check the status the responses they no longer received in the debug mode and i have to restart the script again.

I guess the issue is related to using ESPALEXA with webserver , it revokes the connection from alexa and give it to webserver i had the same problem when i was implementing this on my ESP.

 I then tried the example of using ESP with webserver provided by @aircoookie and that resolved my issue.

Have a look at this https://github.com/Aircoookie/Espalexa/tree/master/examples/EspalexaWithWebServer

Maybe this can be tackled on raspberry's too if it can be handeled in ESP's.

**Comment by ayushjain4484** [comment]
Hello @DarkPixelWolf ,

I think i got the issue the issue was due to the network protocols of my router . I reset my router and reconfigured the protocols and everything now seems to be working fine.
