### ISSUE TITLE
Help needed in starting the script on boot startup for raspberrypi

### ISSUE THREAD

**Issue by ayushjain4484** [DarkPixelWolf/Espalexa-Python#3]
Hello @DarkPixelWolf ,

Can you help me with the script to run on boot on my raspberrypi.

I tried rc.local as well as bashrc method but was unable to run the script on startup.

The error message encountered while setting up the script on bashrc for autostart on boot.
![WhatsApp Image 2019-07-21 at 3 35 34 PM](https://user-images.githubusercontent.com/23170844/61589848-98b2a280-abcd-11e9-86ff-d2cf3c64c047.jpeg)

Please help

**Comment by PyxelFox** [comment]
This is pretty simple, there is a service called systemctl, you can use Google or whatever to search for it, there are plenty good tutorials out there. 
Just search for "raspberry autostart systemctl" or "systemd"

**Comment by ayushjain4484** [comment]
I tried running the script using the systemctl command the service is not starting on boot it shows that the service failed to start.

![new](https://user-images.githubusercontent.com/23170844/61590094-1f1cb380-abd1-11e9-9869-5b911dcfa49e.PNG)

This is the error message which i receive.

Although the service is enabled i have to start it manually after boot then it starts and works fine

**Comment by ayushjain4484** [comment]
i tried making an test script in python3 and tried running the script on boot i am able to run the script without any failure.

No error message is received.

![new1](https://user-images.githubusercontent.com/23170844/61590320-01e9e400-abd5-11e9-934b-4c0a80490e05.PNG)

I think there might be an dependency which causes the script (example.py) to fail on startup.

**Comment by ayushjain4484** [comment]
inserting time.sleep() befoer the script starts worked for me service is up now on boot

Thanks for the help @DarkPixelWolf
